# data_agent.py（更新版）
import json
import subprocess
import sys
import tempfile
import os
import re
from llm import call_llm
from config import CURRENT_TEST_CASE

def clean_code_output(text: str) -> str:
    match = re.search(r"```(?:python)?\s*\n(.*?)\n```", text, re.DOTALL | re.IGNORECASE)
    if match:
        return match.group(1).strip()
    return text.strip()

def generate_paper_data():
    prompt_path = f"test_cases/{CURRENT_TEST_CASE}/data_prompt.txt"
    if not os.path.exists(prompt_path):
        raise FileNotFoundError(f"缺少 data_prompt.txt: {prompt_path}")
    
    with open(prompt_path, "r", encoding="utf-8") as f:
        prompt = f.read()
    
    print(f"🧠 Data Agent 正在为 '{CURRENT_TEST_CASE}' 生成数据抓取脚本...")
    raw_code = call_llm(prompt)
    code = clean_code_output(raw_code)
    
    # ✅ 新增：保存生成的脚本到 outputs/
    generated_script_path = "outputs/generated_data_scraper.py"
    with open(generated_script_path, "w", encoding="utf-8") as f:
        f.write("# -*- coding: utf-8 -*-\n")
        f.write("# This script was auto-generated by Data Agent based on data_prompt.txt\n")
        f.write(code)
    print(f"💾 生成的爬虫脚本已保存: {generated_script_path}")
    
    # 使用该脚本执行
    try:
        print("🕷️ 正在执行生成的爬虫脚本...")
        result = subprocess.run(
            [sys.executable, generated_script_path],
            capture_output=True,
            text=True,
            timeout=60,
            env={**os.environ, 'PYTHONIOENCODING': 'utf-8'}
        )
        
        if result.returncode != 0:
            print(f"❌ 脚本执行失败:\n{result.stderr}")
            raise RuntimeError(f"Data Agent 生成的脚本执行失败 (test case: {CURRENT_TEST_CASE})")
        
        # 解析 JSON 输出
        data = json.loads(result.stdout.strip())
        output_path = "outputs/data.json"
        with open(output_path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        print(f"✅ 真实数据已保存: {output_path}")
            
    except json.JSONDecodeError as e:
        print(f"❌ JSON 解析失败:\n{result.stdout[:500]}...")
        raise RuntimeError(f"Data Agent 输出非有效 JSON: {e}")